cmake_minimum_required(VERSION 3.24)
project(mbuc_secure_copy LANGUAGES C ASM)
add_library(mbuc_secure_copy secure_copy.S)
target_include_directories(mbuc_secure_copy PUBLIC include)
include(CTest)
if(BUILD_TESTING)
  add_executable(mbuc_secure_copy_test test_secure_copy.c)
  target_link_libraries(mbuc_secure_copy_test PRIVATE mbuc_secure_copy)
  add_test(NAME mbuc_secure_copy_test COMMAND mbuc_secure_copy_test)
endif()
